/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APAR = 9;
  /** RegularExpression Id. */
  int FPAR = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int READIO = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINTIO = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int SOMA = 24;
  /** RegularExpression Id. */
  int SUB = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIOR = 31;
  /** RegularExpression Id. */
  int IGUALDADE = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int DEF = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "\";\"",
    "\"float\"",
    "\"bool\"",
    "\":=\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"readIO\"",
    "\"return\"",
    "\"printIO\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"def\"",
    "<NUM>",
    "<ID>",
  };

}
